# Tugas 2 Diskritisasi

Link colab tugas Diskritisasi

https://colab.research.google.com/drive/1ChvOSMjkfehDeMp1k-2TbodVe6f55pbD

In [2]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [4]:
iris = pd.read_csv('https://raw.github.com/NessaRNG/DataMining/gh-pages/Iris.csv')
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
iris.shape

(150, 6)

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer
a = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
iris["SepalLengthCm"] = a.fit_transform(iris[["SepalLengthCm"]])

In [ ]:
iris["SepalLengthCm"]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    1.0
Name: SepalLengthCm, Length: 150, dtype: float64

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer
a = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
iris["SepalWidthCm"] = a.fit_transform(iris[["SepalWidthCm"]])

In [ ]:
iris["SepalWidthCm"]

0      2.0
1      1.0
2      2.0
3      1.0
4      2.0
      ...
145    1.0
146    0.0
147    1.0
148    2.0
149    1.0
Name: SepalWidthCm, Length: 150, dtype: float64

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer
a = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
iris["PetalLengthCm"] = a.fit_transform(iris[["PetalLengthCm"]])

In [ ]:
iris["PetalLengthCm"]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: PetalLengthCm, Length: 150, dtype: float64

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer
a = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
iris["PetalWidthCm"] = a.fit_transform(iris[["PetalWidthCm"]])

In [ ]:
iris["PetalWidthCm"]

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    3.0
146    3.0
147    3.0
148    3.0
149    2.0
Name: PetalWidthCm, Length: 150, dtype: float64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd /content/drive/MyDrive/Github/DataMining

/content/drive/MyDrive/Github/DataMining

In [ ]:
iris.to_csv("equal-width diskritisasi_iris.csv")

In [ ]:
iris1 = pd.read_csv("/content/drive/MyDrive/Github/DataMining/equal-width diskritisasi_iris.csv")
iris1.head()

,Unnamed: 0,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,0,1,0.0,2.0,0.0,0.0,Iris-setosa
1,1,2,0.0,1.0,0.0,0.0,Iris-setosa
2,2,3,0.0,2.0,0.0,0.0,Iris-setosa
3,3,4,0.0,1.0,0.0,0.0,Iris-setosa
4,4,5,0.0,2.0,0.0,0.0,Iris-setosa